name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Hugging Face Space
        uses: huggingface/hub-action@main
        with:
          repo-id: princegarg53/GeochatP
          repo-type: space
          hf-token: ${{ secrets.HF_TOKEN }}
