name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to Hugging Face Space
        uses: huggingface/hub-action@v1  # Use v1 instead of v1.4.4
        with:
          repo-id: Prince53/GeochatP  # Make sure this matches your Hugging Face username and space name
          repo-type: space
          hf-token: ${{ secrets.HF_TOKEN }}
